name: Rebuild

on:
  schedule:
    - cron:  '47 * * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub pages build endpoint
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/navikt/mangfold-i-mai/pages/builds \
            --header "Authorization: Bearer $REBUILD"
        env:
          GH_TOKEN: ${{ secrets.REBUILD }}
